services:
  xash3d:
    image: yohimik/multi-web-server:latest
    build:
      context: ../../
      dockerfile: ./docker/multi-web-server/Dockerfile
      tags:
        - yohimik/multi-web-server:latest
        - yohimik/multi-web-server:${TAG}
    restart: always
    platform: linux/386
    environment:
      GAME_TYPE: "cstrike"
      PORT: 27018
      IP: 192.168.50.123
    volumes:
      - "./valve.zip:/xashds/public/valve.zip"
    ports:
      - "27016:27016"
      - "27018:27018"
      - "27018:27018/udp"